books = [
    {
        "id" : 1,
        "title" : "Think Python",
        "author" : "Allen B. Downey",
        "publisher" : "O'Reilly Media",
        "published_date" : "2021-01-19",
        "page_count" : 1234,
        "language" : "English",
    },
    {
        "id" : 2,
        "title" : "Django By Example",
        "author" : "Antonio Mele",
        "publisher" : "Packt Publishing Ltd",
        "published_date" : "2022-01-19",
        "page_count" : 1023,
        "language" : "English",
    },
    {
        "id" : 3,
        "title" : "The web socket handbook",
        "author" : "Alex Diaconu",
        "publisher" : "Xinyu Wang",
        "published_date" : "2021-01-01",
        "page_count" : 3677,
        "language" : "English",
    },
    {
        "id": 4,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-03-29",
        "page_count": 1014,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Learning Python",
        "author": "Mark Lutz",
        "publisher": "O'Reilly Media",
        "published_date": "2013-06-12",
        "page_count": 1648,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Addison-Wesley Professional",
        "published_date": "2019-02-20",
        "page_count": 320,
        "language": "English",
    }
]
